---
AWSTemplateFormatVersion: "2010-09-09"
Description: Creates ECR repository.

Parameters:
  Repository:
    Description: Name for the ECR repository.
    Type: String

Resources:
  Repository: 
    Type: AWS::ECR::Repository
    Properties: 
      EncryptionConfiguration:
        EncryptionType: AES256
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE
      RepositoryName: !Ref Repository

Outputs:
  Role:
    Value: !GetAtt Role.Arn 
