name: Test

on:
  pull_request:
    branches:
      - master

env:
  DOCKER_BUILDKIT: 1

jobs:
  test-build:
    name: test-build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
      
      # NOTE: we use local images in test workflows
      #       which is why cache is local also
      - name: cache docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: login to DynaTrace Registry
        id: login-dtr
        uses: docker/login-action@v2 
        with:
          registry: ${{ secrets.DYNATRACE_USERNAME }}.live.dynatrace.com
          username: ${{ secrets.DYNATRACE_USERNAME }}
          password: ${{ secrets.DYNATRACE_TOKEN }}

      - name: build docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: opendata/nginx:latest
          outputs: type=docker,dest=/tmp/opendata-nginx-latest.tar
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: build docker image (dynatrace)
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: opendata/nginx:latest-dynatrace
          build-args: |
            DYNATRACE_ENABLED=1
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      
      - name: upload docker image
        uses: actions/upload-artifact@v3
        with:
          name: opendata-nginx-latest
          path: /tmp/opendata-nginx-latest.tar

      # NOTE: Temp fix
      #       https://github.com/docker/build-push-action/issues/252
      #       https://github.com/moby/buildkit/issues/1896
      - name: move docker cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  
  test-image:
    name: test-image
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: ${{ github.ref }}
    needs:
      - test-build
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
      
      - name: download docker image
        uses: actions/download-artifact@v2
        with:
          name: opendata-nginx-latest
          path: /tmp

      - name: load docker image
        run: |
          docker load --input /tmp/opendata-nginx-latest.tar

      - name: validate nginx configs
        run: |
          docker run --name validate \
            -e NGINX_ROOT=/var/www/html \
            -e NGINX_MAX_BODY_SIZE=5000M \
            -e NGINX_EXPIRES=1h \
            -e NGINX_CSP_DEFAULT_SRC="" \
            -e NGINX_CSP_SCRIPT_SRC="" \
            -e NGINX_CSP_STYLE_SRC="" \
            -e NGINX_CSP_FRAME_SRC="" \
            -e NAMESERVER=8.8.8.8 \
            -e NGINX_PORT=80 \
            -e DOMAIN_NAME=localhost \
            -e SECONDARY_DOMAIN_NAME=nginx \
            -e BASE_DOMAIN_NAME=localhost.test \
            -e SECONDARY_BASE_DOMAIN_NAME=nginx.test \
            -e CKAN_HOST=ckan \
            -e CKAN_PORT=5000 \
            -e DRUPAL_HOST=drupal \
            -e DRUPAL_PORT=9000 \
            -t \
            -a \
            stdout opendata/nginx:latest nginx -t

  test-release:
    name: test-release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: semantic release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 18
          branch: master
          dry_run: true
          extra_plugins: |
            @semantic-release/changelog@6.0.1
            @semantic-release/git@10.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
